### ISSUE TITLE
Adding millisecond function to the Every struct impl

### ISSUE THREAD

**Issue by binkabir** [dedefer/tokio_schedule#4]
This lib seems to have a limitation. one cant create  a job less than a fraction of a seconds e.g 
```let every_fraction_second = every(0.5).seconds().perform(|| async { println!("a fraction of a second"} );```

I would suggest an implement of milliseconds on the `Every` Struct

**Comment by dedefer** [comment]
Thank you for your issue 

I'll try to implement milliseconds soon!

**Comment by binkabir** [comment]
That will be nice, I might also send a pull request soon
