### ISSUE TITLE
What happens if a task is not finished until its next schedule comes up?

### ISSUE THREAD

**Issue by danechitoaie** [dedefer/tokio_schedule#9]
What happens if a task is not finished until its next schedule comes up?
So if I have a task that needs to run every 5 mins but sometimes the task takes more than 5 mins to complete, what will happen?

**Comment by dedefer** [comment]
The overlapped task will be skipped. 
I mean that if the next task run must perform in 5 minutes, but the current task will be running for 6 minutes, then the next run will be skipped.

It works that way because there is simple while cycle

```rust
fn perform<'a, F, Fut>(self, mut func: F) -> Pin<Box<dyn Future<Output = ()> + Send + 'a>>
    where
        Self: Send + 'a,
        F: FnMut() -> Fut + Send + 'a,
        Fut: Future<Output = ()> + Send + 'a,
        <Self::TZ as TimeZone>::Offset: Send + 'a,
{
        let fut = async move {
            while let Some(dur) = self.time_to_sleep() {
                sleep(dur).await;
                func().await;
            }
        };

        Box::pin(fut)
    }
}
```

**Comment by danechitoaie** [comment]
So if I schedule a task every 5 mins:

- task takes 4 mins (it's ok, it's under 5mins, so next one will run in 1min from now)
- task takes 6 mins (1 min past, so next one will be skipped, and the one after next will run which is in 4mins from now)

Did I understood correctly?

**Comment by dedefer** [comment]
Yes! You got it right!!

**Comment by danechitoaie** [comment]
Ok, thanks for clarification.
